services:
  postgres:
    image: postgres:17
    container_name: documanDatabase
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./persist/database/postgres:/var/lib/postgresql/data
    tty: true
  redis:
    container_name: redis
    image: redis:7
    volumes:
      - ./persist/redis:/root/redis:rw
    restart: unless-stopped
    ports:
      - 4379:6379
    command: redis-server --requirepass password
    stdin_open: true
    tty: true

