--
-- Documan schema reference.
--
-- Generated from the JPA mapping by SchemaExportTest (PostgreSQL dialect) rather than dumped from
-- a live database, so it cannot silently drift from the entities the way the previous pg_dump
-- snapshot did. Regenerate with:
--
--     mvn test -Dtest=SchemaExportTest && cp target/schema-postgres.sql schema.sql
--
-- The running application still creates and evolves the schema itself via
-- `spring.jpa.hibernate.ddl-auto: update`; this file is documentation and a bootstrap script.
--
-- NOTE: the search_outbox entries below were added by hand because this environment has no
-- container runtime to regenerate from. Re-run ./extract-schema-sql.sh where Docker is
-- available to confirm they match what Hibernate emits.
--
-- Upgrading a database created before votes and favourites moved to explicit join tables? Run
-- SQL/migrate-legacy-vote-tables.sql once, then SQL/load-data.sh for reference data.
--

-- ---------------------------------------------------------------- tables
create table comment (id integer generated by default as identity, post_id integer not null, user_id integer not null, date_created timestamp(6) with time zone not null, date_modified timestamp(6) with time zone not null, downvote_count bigint default 0 not null, upvote_count bigint default 0 not null, version bigint default 0 not null, content TEXT not null, primary key (id));
create table comment_vote (comment_id integer not null, user_id integer not null, date_created timestamp(6) with time zone not null, id bigint generated by default as identity, vote_type varchar(16) not null check ((vote_type in ('UPVOTE','DOWNVOTE'))), primary key (id), constraint uq_comment_vote_comment_user unique (comment_id, user_id));
create table department (id integer generated by default as identity, name varchar(255) not null unique, primary key (id));
create table documan_user (can_comment boolean default false not null, can_post boolean default false not null, department_id integer not null, id integer generated by default as identity, is_verified boolean default false not null, role_id integer not null, semester_id integer not null, terms_of_service boolean default false not null, year_id integer not null, date_created timestamp(6) with time zone not null, date_last_interacted timestamp(6) with time zone not null, version bigint default 0 not null, email varchar(255) not null unique, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null unique, primary key (id));
create table favourite_file (file_id integer not null, user_id integer not null, date_created timestamp(6) with time zone not null, id bigint generated by default as identity, primary key (id), constraint uq_favourite_file_file_user unique (file_id, user_id));
create table favourite_post (post_id integer not null, user_id integer not null, date_created timestamp(6) with time zone not null, id bigint generated by default as identity, primary key (id), constraint uq_favourite_post_post_user unique (post_id, user_id));
create table file (id integer generated by default as identity, subject_id integer not null, date_created timestamp(6) with time zone not null, date_modified timestamp(6) with time zone not null, favourite_count bigint default 0 not null, size bigint not null, version bigint default 0 not null, name varchar(255) not null, object_name varchar(255) not null unique, object_url varchar(255) not null, primary key (id));
create table post (id integer generated by default as identity, user_id integer not null, date_created timestamp(6) with time zone not null, date_modified timestamp(6) with time zone not null, downvote_count bigint default 0 not null, favourite_count bigint default 0 not null, upvote_count bigint default 0 not null, version bigint default 0 not null, content TEXT not null, description TEXT not null, title TEXT not null, primary key (id));
create table post_vote (post_id integer not null, user_id integer not null, date_created timestamp(6) with time zone not null, id bigint generated by default as identity, vote_type varchar(16) not null check ((vote_type in ('UPVOTE','DOWNVOTE'))), primary key (id), constraint uq_post_vote_post_user unique (post_id, user_id));
create table role (id integer generated by default as identity, name varchar(255) not null unique, primary key (id));
create table semester (id integer generated by default as identity, name varchar(255) not null unique, primary key (id));
create table subject (department_id integer not null, id integer generated by default as identity, is_lab boolean not null, is_theory boolean not null, semester_id integer not null, year_id integer not null, version bigint default 0 not null, code varchar(255) not null, name varchar(255) not null, primary key (id));
create table year (id integer generated by default as identity, year varchar(255) not null unique, primary key (id));
create table search_outbox (aggregate_id integer not null, attempts integer default 0 not null, aggregate_type varchar(16) not null, dirty_seq bigint default 1 not null, id bigint generated by default as identity, first_seen_at timestamp(6) with time zone not null, visible_at timestamp(6) with time zone not null, last_error varchar(1000), primary key (id), constraint uq_search_outbox_key unique (aggregate_type, aggregate_id));

-- ---------------------------------------------------------------- indexes
create index idx_comment_post_id on comment (post_id);
create index idx_comment_user_id on comment (user_id);
create index idx_comment_date_created on comment (date_created);
create index idx_comment_vote_comment_id on comment_vote (comment_id);
create index idx_comment_vote_user_id on comment_vote (user_id);
create index idx_user_department_id on documan_user (department_id);
create index idx_user_year_id on documan_user (year_id);
create index idx_user_semester_id on documan_user (semester_id);
create index idx_user_role_id on documan_user (role_id);
create index idx_favourite_file_file_id on favourite_file (file_id);
create index idx_favourite_file_user_id on favourite_file (user_id);
create index idx_favourite_post_post_id on favourite_post (post_id);
create index idx_favourite_post_user_id on favourite_post (user_id);
create index idx_file_name on file (name);
create index idx_file_subject_id on file (subject_id);
create index idx_post_title on post (title);
create index idx_post_user_id on post (user_id);
create index idx_post_date_created on post (date_created);
create index idx_post_vote_post_id on post_vote (post_id);
create index idx_post_vote_user_id on post_vote (user_id);
create index idx_subject_code on subject (code);
create index idx_subject_department_id on subject (department_id);
create index idx_subject_year_id on subject (year_id);
create index idx_subject_semester_id on subject (semester_id);
create index idx_subject_department_year_semester on subject (department_id, year_id, semester_id);
create index idx_search_outbox_visible_at on search_outbox (visible_at, id);

-- ---------------------------------------------------------------- foreign keys
alter table if exists comment add constraint FKs1slvnkuemjsq2kj4h3vhx7i1 foreign key (post_id) references post on delete cascade;
alter table if exists comment add constraint FKci89toijlp7qh68rxobcnyhes foreign key (user_id) references documan_user;
alter table if exists comment_vote add constraint FKsuhgx7catnt6chnndede0wmpr foreign key (comment_id) references comment on delete cascade;
alter table if exists comment_vote add constraint FKibmdbrnjtypmdeskn7279rup5 foreign key (user_id) references documan_user on delete cascade;
alter table if exists documan_user add constraint FKk055jvx3hvt6uorodc4yjsiuf foreign key (department_id) references department;
alter table if exists documan_user add constraint FKhqshe1o7h4vnmxxhl1flxjond foreign key (role_id) references role;
alter table if exists documan_user add constraint FK67p7cn6dt2iu55vvda1qxny9x foreign key (semester_id) references semester;
alter table if exists documan_user add constraint FKlohvqnbiph9wft274dknhmdm6 foreign key (year_id) references year;
alter table if exists favourite_file add constraint FK58ursa877b0wtojbhjb7xr2vh foreign key (file_id) references file on delete cascade;
alter table if exists favourite_file add constraint FK4ixgjss2l7p16vhdcwbiadi0q foreign key (user_id) references documan_user on delete cascade;
alter table if exists favourite_post add constraint FK5d0omafhpmvd0lqgww5anrnbw foreign key (post_id) references post on delete cascade;
alter table if exists favourite_post add constraint FKs9wl6bq6s5109472sgln0hdrv foreign key (user_id) references documan_user on delete cascade;
alter table if exists file add constraint FKl49quetqosw5qjqhb0qouhxe4 foreign key (subject_id) references subject;
alter table if exists post add constraint FKt19o2hx2g5vf15vj9jbf7tsdm foreign key (user_id) references documan_user;
alter table if exists post_vote add constraint FK8ph7fgq4u0fto1tjxjrv8108o foreign key (post_id) references post on delete cascade;
alter table if exists post_vote add constraint FKqg01xr18tupyh8k6vs6wdp1lm foreign key (user_id) references documan_user on delete cascade;
alter table if exists subject add constraint FKs2rgt0imytiyktkr2r9yxp9tw foreign key (department_id) references department;
alter table if exists subject add constraint FKmphheehxn35mmxxh67nnexukv foreign key (semester_id) references semester;
alter table if exists subject add constraint FK88f182fpclx9hfrfi1ti4g9ju foreign key (year_id) references year;
