--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0 (Debian 17.0-1.pgdg120+1)
-- Dumped by pg_dump version 17.0 (Debian 17.0-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: comment; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.comment (
    id integer NOT NULL,
    content text NOT NULL,
    date_created timestamp(6) without time zone NOT NULL,
    date_modified timestamp(6) without time zone NOT NULL,
    post_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.comment OWNER TO root;

--
-- Name: comment_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: department; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.department (
    id integer NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.department OWNER TO root;

--
-- Name: department_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.department ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documan_user; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.documan_user (
    id integer NOT NULL,
    terms_of_service boolean DEFAULT false NOT NULL,
    can_comment boolean DEFAULT false NOT NULL,
    can_post boolean DEFAULT false NOT NULL,
    date_created timestamp(6) without time zone NOT NULL,
    date_last_interacted timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    is_verified boolean DEFAULT false NOT NULL,
    last_name character varying(255),
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    department_id integer NOT NULL,
    role_id integer NOT NULL,
    semester_id integer NOT NULL,
    year_id integer NOT NULL
);


ALTER TABLE public.documan_user OWNER TO root;

--
-- Name: documan_user_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.documan_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documan_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: downvoted_comments; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.downvoted_comments (
    user_id integer NOT NULL,
    comment_id integer NOT NULL
);


ALTER TABLE public.downvoted_comments OWNER TO root;

--
-- Name: downvoted_posts; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.downvoted_posts (
    user_id integer NOT NULL,
    post_id integer NOT NULL
);


ALTER TABLE public.downvoted_posts OWNER TO root;

--
-- Name: favourite_files; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.favourite_files (
    user_id integer NOT NULL,
    file_id integer NOT NULL
);


ALTER TABLE public.favourite_files OWNER TO root;

--
-- Name: favourite_posts; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.favourite_posts (
    user_id integer NOT NULL,
    post_id integer NOT NULL
);


ALTER TABLE public.favourite_posts OWNER TO root;

--
-- Name: file; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.file (
    id integer NOT NULL,
    date_created timestamp(6) without time zone NOT NULL,
    date_modified timestamp(6) without time zone NOT NULL,
    name character varying(255) NOT NULL,
    size bigint NOT NULL,
    uuid uuid DEFAULT gen_random_uuid() NOT NULL,
    subject_id bigint NOT NULL
);


ALTER TABLE public.file OWNER TO root;

--
-- Name: file_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.file ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: post; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.post (
    id integer NOT NULL,
    content text NOT NULL,
    date_created timestamp(6) without time zone NOT NULL,
    date_modified timestamp(6) without time zone NOT NULL,
    description text NOT NULL,
    title text NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.post OWNER TO root;

--
-- Name: post_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.post ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.role (
    id integer NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.role OWNER TO root;

--
-- Name: role_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: semester; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.semester (
    id integer NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.semester OWNER TO root;

--
-- Name: semester_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.semester ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.semester_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subject; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.subject (
    id bigint NOT NULL,
    code character varying(255),
    is_lab boolean,
    is_theory boolean,
    name character varying(255),
    department_id integer NOT NULL,
    semester_id integer NOT NULL,
    year_id integer NOT NULL
);


ALTER TABLE public.subject OWNER TO root;

--
-- Name: subject_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.subject ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subject_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: upvoted_comments; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.upvoted_comments (
    user_id integer NOT NULL,
    comment_id integer NOT NULL
);


ALTER TABLE public.upvoted_comments OWNER TO root;

--
-- Name: upvoted_posts; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.upvoted_posts (
    user_id integer NOT NULL,
    post_id integer NOT NULL
);


ALTER TABLE public.upvoted_posts OWNER TO root;

--
-- Name: year; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.year (
    id integer NOT NULL,
    year character varying(255) NOT NULL
);


ALTER TABLE public.year OWNER TO root;

--
-- Name: year_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.year ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.year_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comment comment_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_pkey PRIMARY KEY (id);


--
-- Name: department department_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT department_pkey PRIMARY KEY (id);


--
-- Name: documan_user documan_user_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.documan_user
    ADD CONSTRAINT documan_user_pkey PRIMARY KEY (id);


--
-- Name: file file_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.file
    ADD CONSTRAINT file_pkey PRIMARY KEY (id);


--
-- Name: department idx_department_name; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT idx_department_name UNIQUE (name);


--
-- Name: file idx_file_uuid; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.file
    ADD CONSTRAINT idx_file_uuid UNIQUE (uuid);


--
-- Name: role idx_role_name; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT idx_role_name UNIQUE (name);


--
-- Name: semester idx_semester_name; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.semester
    ADD CONSTRAINT idx_semester_name UNIQUE (name);


--
-- Name: documan_user idx_user_email; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.documan_user
    ADD CONSTRAINT idx_user_email UNIQUE (email);


--
-- Name: documan_user idx_user_username; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.documan_user
    ADD CONSTRAINT idx_user_username UNIQUE (username);


--
-- Name: year idx_year_name; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.year
    ADD CONSTRAINT idx_year_name UNIQUE (year);


--
-- Name: post post_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT post_pkey PRIMARY KEY (id);


--
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- Name: semester semester_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.semester
    ADD CONSTRAINT semester_pkey PRIMARY KEY (id);


--
-- Name: subject subject_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.subject
    ADD CONSTRAINT subject_pkey PRIMARY KEY (id);


--
-- Name: year year_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.year
    ADD CONSTRAINT year_pkey PRIMARY KEY (id);


--
-- Name: idx_comment_content; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_comment_content ON public.comment USING btree (content);


--
-- Name: idx_comment_post_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_comment_post_id ON public.comment USING btree (post_id);


--
-- Name: idx_comment_user_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_comment_user_id ON public.comment USING btree (user_id);


--
-- Name: idx_downvoted_comments_comment_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_downvoted_comments_comment_id ON public.downvoted_comments USING btree (comment_id);


--
-- Name: idx_downvoted_comments_user_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_downvoted_comments_user_id ON public.downvoted_comments USING btree (user_id);


--
-- Name: idx_downvoted_posts_post_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_downvoted_posts_post_id ON public.downvoted_posts USING btree (post_id);


--
-- Name: idx_downvoted_posts_user_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_downvoted_posts_user_id ON public.downvoted_posts USING btree (user_id);


--
-- Name: idx_favourite_files_file_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_favourite_files_file_id ON public.favourite_files USING btree (file_id);


--
-- Name: idx_favourite_files_user_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_favourite_files_user_id ON public.favourite_files USING btree (user_id);


--
-- Name: idx_favourite_posts_post_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_favourite_posts_post_id ON public.favourite_posts USING btree (post_id);


--
-- Name: idx_favourite_posts_user_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_favourite_posts_user_id ON public.favourite_posts USING btree (user_id);


--
-- Name: idx_file_name; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_file_name ON public.file USING btree (name);


--
-- Name: idx_file_subject_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_file_subject_id ON public.file USING btree (subject_id);


--
-- Name: idx_post_title; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_post_title ON public.post USING btree (title);


--
-- Name: idx_post_user_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_post_user_id ON public.post USING btree (user_id);


--
-- Name: idx_subject_code; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_subject_code ON public.subject USING btree (code);


--
-- Name: idx_subject_department_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_subject_department_id ON public.subject USING btree (department_id);


--
-- Name: idx_subject_semester_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_subject_semester_id ON public.subject USING btree (semester_id);


--
-- Name: idx_subject_year_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_subject_year_id ON public.subject USING btree (year_id);


--
-- Name: idx_upvoted_comments_comment_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_upvoted_comments_comment_id ON public.upvoted_comments USING btree (comment_id);


--
-- Name: idx_upvoted_comments_user_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_upvoted_comments_user_id ON public.upvoted_comments USING btree (user_id);


--
-- Name: idx_upvoted_posts_post_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_upvoted_posts_post_id ON public.upvoted_posts USING btree (post_id);


--
-- Name: idx_upvoted_posts_user_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_upvoted_posts_user_id ON public.upvoted_posts USING btree (user_id);


--
-- Name: idx_user_department_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_user_department_id ON public.documan_user USING btree (department_id);


--
-- Name: idx_user_role_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_user_role_id ON public.documan_user USING btree (role_id);


--
-- Name: idx_user_semester_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_user_semester_id ON public.documan_user USING btree (semester_id);


--
-- Name: idx_user_year_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_user_year_id ON public.documan_user USING btree (year_id);


--
-- Name: documan_user fk67p7cn6dt2iu55vvda1qxny9x; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.documan_user
    ADD CONSTRAINT fk67p7cn6dt2iu55vvda1qxny9x FOREIGN KEY (semester_id) REFERENCES public.semester(id);


--
-- Name: subject fk88f182fpclx9hfrfi1ti4g9ju; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.subject
    ADD CONSTRAINT fk88f182fpclx9hfrfi1ti4g9ju FOREIGN KEY (year_id) REFERENCES public.year(id);


--
-- Name: downvoted_comments fkb342wd2ry567tmkkvlxfq8kq0; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.downvoted_comments
    ADD CONSTRAINT fkb342wd2ry567tmkkvlxfq8kq0 FOREIGN KEY (comment_id) REFERENCES public.comment(id);


--
-- Name: comment fkci89toijlp7qh68rxobcnyhes; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT fkci89toijlp7qh68rxobcnyhes FOREIGN KEY (user_id) REFERENCES public.documan_user(id);


--
-- Name: favourite_files fkcvq9fa8ql7onvurvvy03sd8nv; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.favourite_files
    ADD CONSTRAINT fkcvq9fa8ql7onvurvvy03sd8nv FOREIGN KEY (file_id) REFERENCES public.file(id);


--
-- Name: upvoted_posts fkcw0m6ls1w6393fcc5cjab4qd2; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.upvoted_posts
    ADD CONSTRAINT fkcw0m6ls1w6393fcc5cjab4qd2 FOREIGN KEY (user_id) REFERENCES public.documan_user(id);


--
-- Name: downvoted_posts fkff5chc3kqcwlhd3p35d8f1hhg; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.downvoted_posts
    ADD CONSTRAINT fkff5chc3kqcwlhd3p35d8f1hhg FOREIGN KEY (post_id) REFERENCES public.post(id);


--
-- Name: favourite_posts fkg1dodknfgsg6sc4je2ff4q63a; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.favourite_posts
    ADD CONSTRAINT fkg1dodknfgsg6sc4je2ff4q63a FOREIGN KEY (user_id) REFERENCES public.documan_user(id);


--
-- Name: documan_user fkhqshe1o7h4vnmxxhl1flxjond; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.documan_user
    ADD CONSTRAINT fkhqshe1o7h4vnmxxhl1flxjond FOREIGN KEY (role_id) REFERENCES public.role(id);


--
-- Name: favourite_posts fkj8qp0ooddhj4j23rfb54bn9dk; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.favourite_posts
    ADD CONSTRAINT fkj8qp0ooddhj4j23rfb54bn9dk FOREIGN KEY (post_id) REFERENCES public.post(id);


--
-- Name: documan_user fkk055jvx3hvt6uorodc4yjsiuf; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.documan_user
    ADD CONSTRAINT fkk055jvx3hvt6uorodc4yjsiuf FOREIGN KEY (department_id) REFERENCES public.department(id);


--
-- Name: file fkl49quetqosw5qjqhb0qouhxe4; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.file
    ADD CONSTRAINT fkl49quetqosw5qjqhb0qouhxe4 FOREIGN KEY (subject_id) REFERENCES public.subject(id);


--
-- Name: upvoted_comments fkl9033qj0anqrw30qqyu87lctp; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.upvoted_comments
    ADD CONSTRAINT fkl9033qj0anqrw30qqyu87lctp FOREIGN KEY (comment_id) REFERENCES public.comment(id);


--
-- Name: documan_user fklohvqnbiph9wft274dknhmdm6; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.documan_user
    ADD CONSTRAINT fklohvqnbiph9wft274dknhmdm6 FOREIGN KEY (year_id) REFERENCES public.year(id);


--
-- Name: favourite_files fklpge1emq056bnh4r4w915mr8o; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.favourite_files
    ADD CONSTRAINT fklpge1emq056bnh4r4w915mr8o FOREIGN KEY (user_id) REFERENCES public.documan_user(id);


--
-- Name: upvoted_posts fklx3vur2ucw5sj0hmjvqc5ycl7; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.upvoted_posts
    ADD CONSTRAINT fklx3vur2ucw5sj0hmjvqc5ycl7 FOREIGN KEY (post_id) REFERENCES public.post(id);


--
-- Name: downvoted_posts fkm6bkg6tq77dr587ws6qc0yg2e; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.downvoted_posts
    ADD CONSTRAINT fkm6bkg6tq77dr587ws6qc0yg2e FOREIGN KEY (user_id) REFERENCES public.documan_user(id);


--
-- Name: subject fkmphheehxn35mmxxh67nnexukv; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.subject
    ADD CONSTRAINT fkmphheehxn35mmxxh67nnexukv FOREIGN KEY (semester_id) REFERENCES public.semester(id);


--
-- Name: downvoted_comments fkrhj2bf1mrd2hmcotflk240vc5; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.downvoted_comments
    ADD CONSTRAINT fkrhj2bf1mrd2hmcotflk240vc5 FOREIGN KEY (user_id) REFERENCES public.documan_user(id);


--
-- Name: comment fks1slvnkuemjsq2kj4h3vhx7i1; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT fks1slvnkuemjsq2kj4h3vhx7i1 FOREIGN KEY (post_id) REFERENCES public.post(id);


--
-- Name: subject fks2rgt0imytiyktkr2r9yxp9tw; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.subject
    ADD CONSTRAINT fks2rgt0imytiyktkr2r9yxp9tw FOREIGN KEY (department_id) REFERENCES public.department(id);


--
-- Name: post fkt19o2hx2g5vf15vj9jbf7tsdm; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT fkt19o2hx2g5vf15vj9jbf7tsdm FOREIGN KEY (user_id) REFERENCES public.documan_user(id);


--
-- Name: upvoted_comments fktewbb8fqcfs1e97gaklt0dk4t; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.upvoted_comments
    ADD CONSTRAINT fktewbb8fqcfs1e97gaklt0dk4t FOREIGN KEY (user_id) REFERENCES public.documan_user(id);


--
-- PostgreSQL database dump complete
--

