spring:
  devtools:
    add-properties: false
  application:
    name: "documan"
  data:
    redis:
      password: password
      port: 6379
      host: localhost
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true # remove in staging and production profiles
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
      leak-detection-threshold: 2000
      auto-commit: false
      connection-test-query: SELECT 1
      pool-name: HikariPool
server:
  port: 8080
  tomcat:
    accept-count: 200
    threads:
      max: 400
      min-spare: 20
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024
  error:
    whitelabel:
      enabled: off
logging:
  level:
    org:
      springframework:
        web: debug # set to error in staging and production profiles
      hibernate: warn # set to error in staging and production profiles
    web: warn # set to error in staging and production profiles

